<?php
/**
 * @file
 * wetkit_wetboew.module
 */

include_once 'libraries/wetkit_wetboew.libraries.inc';
include_once 'theme/wetkit_wetboew.theme.inc';

/**
 * Implements hook_page_build().
 */
function wetkit_wetboew_page_build() {
  // Only use WET-BOEW on Front End.
  global $theme;
  global $base_theme_info;
  $wetkit_base_theme = FALSE;
  $themekey = 'theme-gcwu-fegc';

  foreach ($base_theme_info as $base) {
    if (!empty($base->name)) {
      if ($base->name == 'wetkit_adaptivetheme' || $base->name == 'wetkit_omega') {
        $wetkit_base_theme = TRUE;
      }
    }
  }

  if (($theme == 'wetkit_adaptivetheme') || ($theme == 'wetkit_omega') || ($wetkit_base_theme == TRUE)) {
    // Internet Theme.
    $library = libraries_detect('wet-boew', NULL, 'internet');
    if ((isset($library)) && !empty($library['variants']['internet']['installed'])) {
      libraries_load('wet-boew', 'internet');
      $themekey = 'theme-gcwu-fegc';
    }
    // Intranet Theme.
    $library = libraries_detect('wet-boew', NULL, 'intranet');
    if ((isset($library)) && !empty($library['variants']['intranet']['installed'])) {
      libraries_load('wet-boew', 'intranet');
      $themekey = 'theme-gcwu-intranet';
    }
    // Base Theme.
    $library = libraries_detect('wet-boew', NULL, 'base');
    if ((isset($library)) && !empty($library['variants']['base']['installed'])) {
      libraries_load('wet-boew', 'base');
      $themekey = 'theme-base';
    }
    // WET Theme.
    $library = libraries_detect('wet-boew');
    if ((isset($library)) && !empty($library['installed'])) {
      libraries_load('wet-boew');
      $themekey = 'theme-wet-boew';
    }
  }

  // Solve some of the display inconsistencies between WET and Drupal.
  drupal_add_css(drupal_get_path('module', 'wetkit_wetboew') . '/css/wetkit_wetboew.css', array(
    'group' => CSS_THEME,
    'every_page' => TRUE,
  ));

  // Add the jQuery Mobile Library WET needs.
  if (!user_is_logged_in()) {
    drupal_add_js(libraries_get_path('wet-boew') . '/dist/js/jquerymobile/jquery.mobile.min.js', array(
      'preprocess' => FALSE,
      'scope' => 'footer',
      'weight' => 5,
    ));
  }

  // Add the noscipt css that WET expects.
  $element = array(
    '#type' => 'markup',
    '#markup' => '<link rel="stylesheet" href="' . libraries_get_path('wet-boew', TRUE) . '/dist/' . $themekey . '/css/theme-ns-min.css" />',
    '#prefix' => "<noscript>",
    '#suffix' => "</noscript>\n",
    '#weight' => '999',
  );
  drupal_add_html_head($element, 'wetkit_wetboew_noscript');
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function wetkit_wetboew_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_apps_app_info().
 */
function wetkit_wetboew_apps_app_info() {
  return array(
    'configure form' => 'wetkit_wetboew_configure_form',
  );
}

/**
 * Configuration Form for WetKit WET-BOEW.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param array $form_state
 *   A keyed array containing the current state of the form.
 */
function wetkit_wetboew_configure_form($form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'system') . '/system.js');
  $form = array();
  $form['wetkit_wetboew'] = array(
    '#type' => 'fieldset',
    '#title' => t('WxT Theme Selection'),
    '#collapsible' => TRUE,
  );
  $form['wetkit_wetboew']['wetkit_wetboew_theme'] = array(
    '#type' => 'select',
    '#title' => t('Please choose the desired theme:'),
    '#options' => array(
      0 => t('WxT'),
      1 => t('Internet'),
      2 => t('Intranet'),
      3 => t('Base Theme'),
    ),
    '#default_value' => variable_get('wetkit_wetboew_theme', 0),
    '#description' => t('This will change the theme by adding custom css and logic to support the various Drupal WxT based themes.'),
  );

  $form['#submit'][] = 'wetkit_wetboew_configure_form_submit';

  return system_settings_form($form);
}

/**
 * Handle submission of the WetKit Web Usability configuration page.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param array $form_state
 *   A keyed array containing the current state of the form.
 */
function wetkit_wetboew_configure_form_submit($form, &$form_state) {
  // Change query-strings on css/js files to enforce reload for all users.
  _drupal_flush_css_js();

  registry_rebuild();
  drupal_clear_css_cache();
  drupal_clear_js_cache();

  // Rebuild the theme data. Note that the module data is rebuilt above, as
  // part of registry_rebuild().
  system_rebuild_theme_data();
  drupal_theme_rebuild();

  // Don't clear cache_form - in-progress form submissions may break.
  // Ordered so clearing the page cache will always be the last action.
  $core = array(
    'cache',
    'cache_path',
    'cache_filter',
    'cache_bootstrap',
    'cache_page',
  );
  $cache_tables = array_merge(module_invoke_all('flush_caches'), $core);
  foreach ($cache_tables as $table) {
    cache_clear_all('*', $table, TRUE);
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function wetkit_wetboew_theme_registry_alter(&$theme_registry) {
  if (module_exists('total_control')) {
    $theme_registry['total_control_admin_table']['theme path'] = drupal_get_path('module', 'wetkit_wetboew');
    $theme_registry['total_control_admin_table']['file'] = drupal_get_path('module', 'wetkit_wetboew') . '/theme/wetkit_wetboew.theme.inc';
    $theme_registry['total_control_admin_table']['function'] = 'theme_wetkit_wetboew_admin_table';
    $theme_registry['total_control_admin_table']['final'] = TRUE;
  }
}

/**
 * Implements hook_css_alter().
 */
function wetkit_wetboew_css_alter(&$css) {
  // Unsets some non essential jquery ui effects.
  if (isset($css['misc/ui/jquery.ui.dialog.css'])) {
    unset($css['misc/ui/jquery.ui.dialog.css']);
  }

  if (isset($css['misc/ui/jquery.ui.tabs.css'])) {
    unset($css['misc/ui/jquery.ui.tabs.css']);
  }
}

/**
 * Implements hook_theme().
 */
function wetkit_wetboew_theme($existing, $type, $theme, $path) {
  return array(
    'wetkit_wetboew_admin_table' => array(
      'render element' => 'element',
      'file' => 'theme/wetkit_wetboew.theme.inc',
    ),
    'wetkit_wetboew_status_messages' => array(
      'render element' => 'element',
      'file' => 'theme/wetkit_wetboew.theme.inc',
    ),
    'wetkit_wetboew_tablefield_view' => array(
      'file' => 'theme/wetkit_wetboew.theme.inc',
      'variables' => array(
        'header' => NULL,
        'rows' => NULL,
        'delta' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_status_messages().
 */
function wetkit_wetboew_preprocess_status_messages(&$variables) {
  global $theme;
  global $base_theme_info;
  $wetkit_base_theme = FALSE;

  foreach ($base_theme_info as $base) {
    if (!empty($base->name)) {
      if ($base->name == 'wetkit_adaptivetheme' || $base->name == 'wetkit_omega') {
        $wetkit_base_theme = TRUE;
      }
    }
  }

  if (($theme == 'wetkit_adaptivetheme') || ($theme == 'wetkit_omega') || ($wetkit_base_theme == TRUE)) {
    $variables['theme_hook_suggestions'][] = 'wetkit_wetboew_status_messages';
  }
}

/**
 * Implements hook_preprocess_tablefield_view().
 */
function wetkit_wetboew_preprocess_tablefield_view(&$variables) {
  global $theme;
  global $base_theme_info;
  $wetkit_base_theme = FALSE;

  foreach ($base_theme_info as $base) {
    if (!empty($base->name)) {
      if ($base->name == 'wetkit_adaptivetheme' || $base->name == 'wetkit_omega') {
        $wetkit_base_theme = TRUE;
      }
    }
  }

  if (($theme == 'wetkit_adaptivetheme') || ($theme == 'wetkit_omega') || ($wetkit_base_theme == TRUE)) {
    $variables['theme_hook_suggestions'][] = 'wetkit_wetboew_tablefield_view';
  }
}
